import 'bloc/tipos_de_sesion_bloc.dart';import 'models/tipos_de_sesion_model.dart';import 'package:flutter/material.dart';import 'package:pedidos/core/app_export.dart';import 'package:pedidos/widgets/app_bar/appbar_leading_image.dart';import 'package:pedidos/widgets/app_bar/appbar_title.dart';import 'package:pedidos/widgets/app_bar/custom_app_bar.dart';class TiposDeSesionScreen extends StatelessWidget {const TiposDeSesionScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<TiposDeSesionBloc>(create: (context) => TiposDeSesionBloc(TiposDeSesionState(tiposDeSesionModelObj: TiposDeSesionModel()))..add(TiposDeSesionInitialEvent()), child: TiposDeSesionScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<TiposDeSesionBloc, TiposDeSesionState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 49.h, vertical: 31.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgGroup, height: 66.v, width: 228.h), Spacer(flex: 34), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(children: [GestureDetector(onTap: () {onTapFrame(context);}, child: Container(height: 98.v, width: 101.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 16.v), decoration: AppDecoration.fillBlue.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: CustomImageView(imagePath: ImageConstant.imgBg, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(32.h), alignment: Alignment.center))), SizedBox(height: 9.v), Text("lbl_touch_id".tr, style: TextStyle(color: appTheme.black900, fontSize: 20.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w600))]), Column(children: [GestureDetector(onTap: () {onTapFaceIDIcon1(context);}, child: Container(height: 98.v, width: 101.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 16.v), decoration: AppDecoration.fillBlue.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: CustomImageView(imagePath: ImageConstant.imgCalendar, height: 64.adaptSize, width: 64.adaptSize, alignment: Alignment.center))), SizedBox(height: 10.v), Text("lbl_face_id".tr, style: TextStyle(color: appTheme.black900, fontSize: 20.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w600))])]), SizedBox(height: 44.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 39.h), child: Text("msg_registra_un_tipo".tr, style: TextStyle(color: appTheme.blueGray300, fontSize: 19.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w600)))), SizedBox(height: 47.v), Text("msg_iniciar_sin_touch".tr, style: TextStyle(color: appTheme.blueGray300, fontSize: 14.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w400, decoration: TextDecoration.underline)), Spacer(flex: 65)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 67.v, leadingWidth: 68.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 44.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_bienvenido_leo".tr)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the touchIdScreen when the action is triggered.
onTapFrame(BuildContext context) { NavigatorService.pushNamed(AppRoutes.touchIdScreen, ); } 
/// Navigates to the faceIdScreen when the action is triggered.
onTapFaceIDIcon1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.faceIdScreen, ); } 
 }
