import 'bloc/menu_seguridad_bloc.dart';import 'models/menu_seguridad_model.dart';import 'package:flutter/material.dart';import 'package:pedidos/core/app_export.dart';import 'package:pedidos/presentation/pedidos_detalle_page/pedidos_detalle_page.dart';import 'package:pedidos/widgets/custom_bottom_bar.dart';import 'package:pedidos/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class MenuSeguridadScreen extends StatelessWidget {MenuSeguridadScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<MenuSeguridadBloc>(create: (context) => MenuSeguridadBloc(MenuSeguridadState(menuSeguridadModelObj: MenuSeguridadModel()))..add(MenuSeguridadInitialEvent()), child: MenuSeguridadScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 41.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 29.h), child: BlocSelector<MenuSeguridadBloc, MenuSeguridadState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_buscar".tr, alignment: Alignment.center, contentPadding: EdgeInsets.only(left: 23.h, top: 5.v, bottom: 5.v));}))), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 29.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle82, height: 64.v, width: 63.h, radius: BorderRadius.circular(27.h)), Padding(padding: EdgeInsets.only(left: 20.h, top: 7.v, bottom: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_leo_gutierrez".tr, style: TextStyle(color: appTheme.black900, fontSize: 20.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700)), SizedBox(height: 1.v), Text("msg_imshuvo97_gmail_com".tr, style: TextStyle(color: theme.colorScheme.onError, fontSize: 16.fSize, fontFamily: 'Gilroy-Regular', fontWeight: FontWeight.w400))]))])), SizedBox(height: 37.v), Padding(padding: EdgeInsets.only(left: 29.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgBackArrow, height: 14.v, width: 8.h, margin: EdgeInsets.only(top: 1.v, bottom: 4.v)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("lbl_seguridad".tr, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600)))])), SizedBox(height: 33.v), Divider(color: appTheme.gray30001), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 29.h, right: 32.h), child: _buildAgregarFaceID(context, dynamicTextProp: "msg_cambiar_contrase_a".tr)), SizedBox(height: 21.v), _buildTwenty(context), SizedBox(height: 20.v), _buildAgregarUnTipo(context), SizedBox(height: 19.v), _buildTwenty(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 29.h, right: 32.h), child: _buildAgregarFaceID(context, dynamicTextProp: "lbl_agregar_face_id".tr)), SizedBox(height: 19.v), Divider(color: appTheme.gray30001), SizedBox(height: 5.v)])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: _buildBottomBar(context)))); } 
/// Section Widget
Widget _buildAgregarUnTipo(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 24.h, right: 32.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [GestureDetector(onTap: () {onTapTxtAgregarUnTipo(context);}, child: Text("msg_agregar_un_tipo".tr, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600))), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 14.v, width: 8.h, margin: EdgeInsets.only(top: 3.v, bottom: 2.v))]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
/// Common widget
Widget _buildTwenty(BuildContext context) { return SizedBox(height: 1.v, width: 413.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 413.h, child: Divider(color: appTheme.gray30001))), Align(alignment: Alignment.center, child: SizedBox(width: 413.h, child: Divider(color: appTheme.gray30001)))])); } 
/// Common widget
Widget _buildAgregarFaceID(BuildContext context, {required String dynamicTextProp, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(dynamicTextProp, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600)), CustomImageView(imagePath: ImageConstant.imgBackArrowGray90001, height: 14.v, width: 8.h, margin: EdgeInsets.only(bottom: 4.v))]); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.pedidosDetallePage; case BottomBarEnum.Rutas: return "/"; case BottomBarEnum.Courses: return "/"; case BottomBarEnum.Cobrar: return "/"; case BottomBarEnum.Clientes: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.pedidosDetallePage: return PedidosDetallePage.builder(context); default: return DefaultWidget();} } 
/// Navigates to the tiposDeSesionScreen when the action is triggered.
onTapTxtAgregarUnTipo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.tiposDeSesionScreen, ); } 
 }
