import 'bloc/datos_empresa_bloc.dart';import 'models/datos_empresa_model.dart';import 'package:flutter/material.dart';import 'package:outline_gradient_button/outline_gradient_button.dart';import 'package:pedidos/core/app_export.dart';import 'package:pedidos/core/utils/validation_functions.dart';import 'package:pedidos/widgets/app_bar/appbar_leading_image.dart';import 'package:pedidos/widgets/app_bar/appbar_title.dart';import 'package:pedidos/widgets/app_bar/custom_app_bar.dart';import 'package:pedidos/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class DatosEmpresaScreen extends StatelessWidget {DatosEmpresaScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<DatosEmpresaBloc>(create: (context) => DatosEmpresaBloc(DatosEmpresaState(datosEmpresaModelObj: DatosEmpresaModel()))..add(DatosEmpresaInitialEvent()), child: DatosEmpresaScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(height: 884.v, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 9.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 100.v, width: double.maxFinite, margin: EdgeInsets.only(bottom: 5.v), decoration: BoxDecoration())), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 35.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(context), SizedBox(height: 34.v), CustomImageView(imagePath: ImageConstant.imgGroup, height: 66.v, width: 228.h), SizedBox(height: 26.v), Text("msg_datos_de_la_empresa".tr, style: TextStyle(color: appTheme.blue900, fontSize: 20.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700)), SizedBox(height: 33.v), Align(alignment: Alignment.centerLeft, child: Text("msg_tipo_de_documento".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 15.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700))), SizedBox(height: 8.v), BlocSelector<DatosEmpresaBloc, DatosEmpresaState, TextEditingController?>(selector: (state) => state.taxIDController, builder: (context, taxIDController) {return CustomTextFormField(controller: taxIDController, hintText: "lbl_ruc".tr);}), SizedBox(height: 42.v), Align(alignment: Alignment.centerLeft, child: Text("msg_n_mero_de_documento".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 15.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700))), SizedBox(height: 10.v), BlocSelector<DatosEmpresaBloc, DatosEmpresaState, TextEditingController?>(selector: (state) => state.valueController, builder: (context, valueController) {return CustomTextFormField(controller: valueController, hintText: "lbl_12345678910".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.outlinePrimaryTL14);}), SizedBox(height: 34.v), _buildFrame(context)])))]))))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 28.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgUser, margin: EdgeInsets.only(left: 35.h)), title: AppbarTitle(text: "lbl_atr_s".tr, margin: EdgeInsets.only(left: 8.h))); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return SizedBox(height: 66.v, width: 358.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_verificar".tr, style: TextStyle(color: appTheme.pink300, fontSize: 25.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700)), CustomImageView(imagePath: ImageConstant.imgArrowright10x17, height: 10.v, width: 17.h, margin: EdgeInsets.only(left: 22.h, top: 10.v, bottom: 9.v))])), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapView(context);}, child: OutlineGradientButton(padding: EdgeInsets.only(left: 4.h, top: 4.v, right: 4.h, bottom: 4.v), strokeWidth: 4.h, gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.pink300, appTheme.blue900.withOpacity(0.89), theme.colorScheme.primary]), corners: Corners(topLeft: Radius.circular(15), topRight: Radius.circular(15), bottomLeft: Radius.circular(15), bottomRight: Radius.circular(15)), child: Container(height: 66.v, width: 358.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(15.h))))))])); } 
/// Navigates to the datosDelUsuarioScreen when the action is triggered.
onTapView(BuildContext context) { NavigatorService.pushNamed(AppRoutes.datosDelUsuarioScreen, ); } 
 }
