import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import 'package:pedidos/presentation/buscador_de_cliente_screen/models/buscador_de_cliente_model.dart';part 'buscador_de_cliente_event.dart';part 'buscador_de_cliente_state.dart';/// A bloc that manages the state of a BuscadorDeCliente according to the event that is dispatched to it.
class BuscadorDeClienteBloc extends Bloc<BuscadorDeClienteEvent, BuscadorDeClienteState> {BuscadorDeClienteBloc(BuscadorDeClienteState initialState) : super(initialState) { on<BuscadorDeClienteInitialEvent>(_onInitialize); on<ChangeDropDownEvent>(_changeDropDown); on<ChangeDropDown1Event>(_changeDropDown1); on<ChangeDropDown2Event>(_changeDropDown2); }

_changeDropDown(ChangeDropDownEvent event, Emitter<BuscadorDeClienteState> emit, ) { emit(state.copyWith(selectedDropDownValue: event.value)); } 
_changeDropDown1(ChangeDropDown1Event event, Emitter<BuscadorDeClienteState> emit, ) { emit(state.copyWith(selectedDropDownValue1: event.value)); } 
_changeDropDown2(ChangeDropDown2Event event, Emitter<BuscadorDeClienteState> emit, ) { emit(state.copyWith(selectedDropDownValue2: event.value)); } 
List<SelectionPopupModel> fillDropdownItemList() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList1() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList2() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
_onInitialize(BuscadorDeClienteInitialEvent event, Emitter<BuscadorDeClienteState> emit, ) async  { emit(state.copyWith(consultantController: TextEditingController(), valueController: TextEditingController())); emit(state.copyWith(buscadorDeClienteModelObj: state.buscadorDeClienteModelObj?.copyWith(dropdownItemList: fillDropdownItemList(), dropdownItemList1: fillDropdownItemList1(), dropdownItemList2: fillDropdownItemList2()))); } 
 }
