import 'bloc/mas_bloc.dart';import 'models/mas_model.dart';import 'package:flutter/material.dart';import 'package:pedidos/core/app_export.dart';import 'package:pedidos/presentation/pedidos_detalle_page/pedidos_detalle_page.dart';import 'package:pedidos/widgets/custom_bottom_bar.dart';import 'package:pedidos/widgets/custom_outlined_button.dart';import 'package:pedidos/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class MasScreen extends StatelessWidget {MasScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<MasBloc>(create: (context) => MasBloc(MasState(masModelObj: MasModel()))..add(MasInitialEvent()), child: MasScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 32.h, right: 26.h), child: BlocSelector<MasBloc, MasState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_buscar".tr, alignment: Alignment.center, contentPadding: EdgeInsets.only(left: 23.h, top: 5.v, bottom: 5.v));}))), SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 32.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle82, height: 64.v, width: 63.h, radius: BorderRadius.circular(27.h)), Padding(padding: EdgeInsets.only(left: 20.h, top: 7.v, bottom: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_leo_gutierrez".tr, style: TextStyle(color: appTheme.black900, fontSize: 20.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700)), SizedBox(height: 1.v), Text("msg_imshuvo97_gmail_com".tr, style: TextStyle(color: theme.colorScheme.onError, fontSize: 16.fSize, fontFamily: 'Gilroy-Regular', fontWeight: FontWeight.w400))]))]))), SizedBox(height: 16.v), Divider(color: appTheme.gray30001), SizedBox(height: 17.v), _buildFrameRow(context), SizedBox(height: 18.v), _buildTwentySixStack(context), SizedBox(height: 17.v), _buildFrameRow1(context), SizedBox(height: 18.v), Divider(color: appTheme.gray30001), SizedBox(height: 17.v), _buildFrameRow2(context), SizedBox(height: 18.v), Divider(color: appTheme.gray30001), SizedBox(height: 17.v), _buildSearchRow(context), SizedBox(height: 18.v), Divider(color: appTheme.gray30001), SizedBox(height: 17.v), _buildFrameRow3(context), Spacer(), SizedBox(height: 33.v), CustomOutlinedButton(text: "lbl_cerrar_sesi_n".tr, margin: EdgeInsets.only(left: 17.h, right: 32.h), leftIcon: Container(margin: EdgeInsets.only(right: 30.h), child: CustomImageView(imagePath: ImageConstant.imgArrowleftRedA700, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.outlineRedA, onPressed: () {onTapCerrarSesin(context);}, alignment: Alignment.centerLeft)])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: _buildBottomBar(context)))); } 
/// Section Widget
Widget _buildFrameRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 43.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgLock, height: 25.v, width: 20.h), Spacer(flex: 21), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_mi_cuenta".tr, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600))), Spacer(flex: 78), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 14.v, width: 8.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])); } 
/// Section Widget
Widget _buildTwentySixStack(BuildContext context) { return SizedBox(height: 1.v, width: 413.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 413.h, child: Divider(color: appTheme.gray30001))), Align(alignment: Alignment.center, child: SizedBox(width: 413.h, child: Divider(color: appTheme.gray30001)))])); } 
/// Section Widget
Widget _buildFrameRow1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 43.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 136.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgPeoplefill, height: 25.v, width: 27.h), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_clientes".tr, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600)))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 14.v, width: 8.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])); } 
/// Section Widget
Widget _buildFrameRow2(BuildContext context) { return GestureDetector(onTap: () {onTapFrameRow(context);}, child: Padding(padding: EdgeInsets.only(left: 43.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 152.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgTrophy, height: 25.v, width: 20.h), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_seguridad".tr, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600)))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 14.v, width: 8.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))]))); } 
/// Section Widget
Widget _buildSearchRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 43.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 182.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgSearch, height: 25.v, width: 23.h), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_configuraci_n".tr, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600)))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 14.v, width: 8.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])); } 
/// Section Widget
Widget _buildFrameRow3(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 43.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 121.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgProfile, height: 25.adaptSize, width: 25.adaptSize), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_ayuda".tr, style: TextStyle(color: appTheme.black900, fontSize: 16.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600)))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 14.v, width: 8.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.pedidosDetallePage; case BottomBarEnum.Rutas: return "/"; case BottomBarEnum.Courses: return "/"; case BottomBarEnum.Cobrar: return "/"; case BottomBarEnum.Clientes: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.pedidosDetallePage: return PedidosDetallePage.builder(context); default: return DefaultWidget();} } 
/// Navigates to the menuSeguridadScreen when the action is triggered.
onTapFrameRow(BuildContext context) { NavigatorService.pushNamed(AppRoutes.menuSeguridadScreen, ); } 
/// Navigates to the datosEmpresaScreen when the action is triggered.
onTapCerrarSesin(BuildContext context) { NavigatorService.pushNamed(AppRoutes.datosEmpresaScreen, ); } 
 }
