import 'bloc/pedidos_cliente_pendientes_bloc.dart';import 'models/pedidos_cliente_pendientes_model.dart';import 'package:flutter/material.dart';import 'package:pedidos/core/app_export.dart';import 'package:pedidos/widgets/custom_text_form_field.dart';class PedidosClientePendientesPage extends StatefulWidget {const PedidosClientePendientesPage({Key? key}) : super(key: key);

@override PedidosClientePendientesPageState createState() =>  PedidosClientePendientesPageState();

static Widget builder(BuildContext context) { return BlocProvider<PedidosClientePendientesBloc>(create: (context) => PedidosClientePendientesBloc(PedidosClientePendientesState(pedidosClientePendientesModelObj: PedidosClientePendientesModel()))..add(PedidosClientePendientesInitialEvent()), child: PedidosClientePendientesPage()); } 
 }
class PedidosClientePendientesPageState extends State<PedidosClientePendientesPage> with  AutomaticKeepAliveClientMixin<PedidosClientePendientesPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 27.v), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: Column(children: [Padding(padding: EdgeInsets.only(left: 19.h, right: 9.h), child: BlocSelector<PedidosClientePendientesBloc, PedidosClientePendientesState, TextEditingController?>(selector: (state) => state.dateController, builder: (context, dateController) {return CustomTextFormField(controller: dateController, hintText: "msg_mi_rcoles_1_de".tr, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);})), SizedBox(height: 16.v), _buildSeccionDos(context), SizedBox(height: 18.v), Divider(indent: 19.h, endIndent: 9.h), SizedBox(height: 15.v), _buildSeccionTres(context), SizedBox(height: 18.v), Divider(indent: 19.h, endIndent: 9.h), Spacer(), _buildClienteMassSAC(context), SizedBox(height: 10.v), _buildBottomBar(context)])))])))); } 
/// Section Widget
Widget _buildSeccionDos(BuildContext context) { return GestureDetector(onTap: () {onTapSeccionDos(context);}, child: Padding(padding: EdgeInsets.symmetric(horizontal: 27.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 6.v, bottom: 4.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_pedido_245879975".tr, style: TextStyle(color: appTheme.black900, fontSize: 18.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w400)), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 4.v), child: Text("lbl_pendiente".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer, fontSize: 12.fSize, fontFamily: 'Roboto', fontWeight: FontWeight.w500)))]))), CustomImageView(imagePath: ImageConstant.imgArrowRightOnprimarycontainer, height: 33.v, width: 12.h, margin: EdgeInsets.only(left: 32.h))]))); } 
/// Section Widget
Widget _buildSeccionTres(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 27.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 6.v, bottom: 4.v), child: Text("msg_pedido_256478912".tr, style: TextStyle(color: appTheme.black900, fontSize: 18.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w400))), Spacer(flex: 75), Padding(padding: EdgeInsets.only(top: 9.v, bottom: 8.v), child: Text("lbl_pendiente".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer, fontSize: 12.fSize, fontFamily: 'Roboto', fontWeight: FontWeight.w500))), Spacer(flex: 25), CustomImageView(imagePath: ImageConstant.imgArrowRightOnprimarycontainer, height: 33.v, width: 12.h)])); } 
/// Section Widget
Widget _buildClienteMassSAC(BuildContext context) { return Container(margin: EdgeInsets.only(right: 2.h), padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 4.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_cliente_mass_s_a_c2".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 16.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w900)), Text("msg_encargado_cesar".tr, style: TextStyle(color: appTheme.pink300, fontSize: 16.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w900)), Text("msg_calle_cesar_canevaro".tr, style: TextStyle(color: appTheme.gray500, fontSize: 15.fSize, fontFamily: 'Roboto', fontWeight: FontWeight.w400))])), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 12.v, width: 26.h, margin: EdgeInsets.only(top: 20.v, right: 5.h, bottom: 21.v))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 22.v), decoration: AppDecoration.fillGray10004.copyWith(borderRadius: BorderRadiusStyle.customBorderTL15), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 40.v, width: 52.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.bottomRight, child: Text("lbl_home".tr, style: TextStyle(color: appTheme.blueGray800, fontSize: 14.fSize, fontFamily: 'HKGrotesk', fontWeight: FontWeight.w400))), Padding(padding: EdgeInsets.only(right: 12.h), child: _buildRutas(context, bookmarkImage: ImageConstant.imgBookmark1, rutas: "lbl_inicio".tr, onTapRutas: () {onTapRutas(context);}))])), Spacer(flex: 31), _buildRutas(context, bookmarkImage: ImageConstant.imgBookmark1Black900, rutas: "lbl_rutas".tr, onTapRutas: () {onTapRutas1(context);}), Spacer(flex: 30), SizedBox(height: 40.v, width: 57.h, child: Stack(alignment: Alignment.centerRight, children: [Align(alignment: Alignment.bottomCenter, child: Text("lbl_courses".tr, textAlign: TextAlign.center, style: TextStyle(color: appTheme.indigoA200, fontSize: 14.fSize, fontFamily: 'HKGrotesk', fontWeight: FontWeight.w700))), Align(alignment: Alignment.centerRight, child: Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(right: 5.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgBookmark128x40, height: 28.v, width: 40.h, alignment: Alignment.topCenter), Align(alignment: Alignment.bottomCenter, child: Text("lbl_pedidos".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 10.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600)))])))])), Spacer(flex: 37), _buildRutas(context, bookmarkImage: ImageConstant.imgNavCobrar, rutas: "lbl_cobrar".tr, onTapRutas: () {onTapRutas2(context);}), Container(height: 40.v, width: 54.h, margin: EdgeInsets.only(left: 22.h), child: Stack(alignment: Alignment.centerRight, children: [Align(alignment: Alignment.bottomLeft, child: Text("lbl_profile".tr, textAlign: TextAlign.right, style: TextStyle(color: appTheme.blueGray800, fontSize: 14.fSize, fontFamily: 'HKGrotesk', fontWeight: FontWeight.w400))), Padding(padding: EdgeInsets.only(left: 14.h), child: _buildRutas(context, bookmarkImage: ImageConstant.imgNavClientes, rutas: "lbl_clientes".tr, onTapRutas: () {onTapRutas3(context);}))]))])), SizedBox(height: 6.v), SizedBox(width: 60.h, child: Divider(color: theme.colorScheme.primary))])); } 
/// Common widget
Widget _buildRutas(BuildContext context, {required String bookmarkImage, required String rutas, Function? onTapRutas, }) { return GestureDetector(onTap: () {onTapRutas!.call();}, child: Column(children: [CustomImageView(imagePath: bookmarkImage, height: 28.v, width: 40.h), Text(rutas, style: TextStyle(color: appTheme.black900, fontSize: 10.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w600))])); } 
/// Navigates to the detallesDePedidoFacturaScreen when the action is triggered.
onTapSeccionDos(BuildContext context) { NavigatorService.pushNamed(AppRoutes.detallesDePedidoFacturaScreen, ); } 
/// Navigates to the panelPrincipalScreen when the action is triggered.
onTapRutas(BuildContext context) { NavigatorService.pushNamed(AppRoutes.panelPrincipalScreen, ); } 
/// Navigates to the rutasTabContainerScreen when the action is triggered.
onTapRutas1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.rutasTabContainerScreen, ); } 
/// Navigates to the cobrarScreen when the action is triggered.
onTapRutas2(BuildContext context) { NavigatorService.pushNamed(AppRoutes.cobrarScreen, ); } 
/// Navigates to the masScreen when the action is triggered.
onTapRutas3(BuildContext context) { NavigatorService.pushNamed(AppRoutes.masScreen, ); } 
 }
