import 'bloc/datos_del_usuario_one_bloc.dart';import 'models/datos_del_usuario_one_model.dart';import 'package:flutter/material.dart';import 'package:outline_gradient_button/outline_gradient_button.dart';import 'package:pedidos/core/app_export.dart';import 'package:pedidos/widgets/app_bar/appbar_leading_image.dart';import 'package:pedidos/widgets/app_bar/appbar_title.dart';import 'package:pedidos/widgets/app_bar/custom_app_bar.dart';import 'package:pedidos/widgets/custom_checkbox_button.dart';import 'package:pedidos/widgets/custom_text_form_field.dart';class DatosDelUsuarioOneScreen extends StatelessWidget {const DatosDelUsuarioOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<DatosDelUsuarioOneBloc>(create: (context) => DatosDelUsuarioOneBloc(DatosDelUsuarioOneState(datosDelUsuarioOneModelObj: DatosDelUsuarioOneModel()))..add(DatosDelUsuarioOneInitialEvent()), child: DatosDelUsuarioOneScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 35.h, vertical: 24.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgGroup, height: 66.v, width: 228.h, alignment: Alignment.center), SizedBox(height: 23.v), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_empresa".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 20.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700))), Padding(padding: EdgeInsets.only(left: 10.h, bottom: 2.v), child: Text("lbl_gloria_s_a_c".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 20.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w800)))])), SizedBox(height: 24.v), Align(alignment: Alignment.center, child: Text("msg_ingresa_tus_datos".tr, style: TextStyle(color: appTheme.blue900, fontSize: 20.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700))), SizedBox(height: 31.v), Text("lbl_usuario".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 15.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700)), SizedBox(height: 10.v), BlocSelector<DatosDelUsuarioOneBloc, DatosDelUsuarioOneState, TextEditingController?>(selector: (state) => state.enterYourUserController, builder: (context, enterYourUserController) {return CustomTextFormField(controller: enterYourUserController, hintText: "msg_ingresa_tu_usuario".tr);}), SizedBox(height: 42.v), Text("lbl_contrase_a".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 15.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700)), SizedBox(height: 10.v), BlocSelector<DatosDelUsuarioOneBloc, DatosDelUsuarioOneState, TextEditingController?>(selector: (state) => state.enterYourPasswordController, builder: (context, enterYourPasswordController) {return CustomTextFormField(controller: enterYourPasswordController, hintText: "msg_ingresa_tu_contrase_a".tr, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.outlinePrimaryTL14);}), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("msg_ha_olvidado_su".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 15.fSize, fontFamily: 'Roboto', fontWeight: FontWeight.w600, decoration: TextDecoration.underline))), SizedBox(height: 29.v), _buildCheckBox(context), SizedBox(height: 23.v), _buildEnterUserFrame(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 47.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgUser, margin: EdgeInsets.only(left: 35.h, top: 9.v, bottom: 9.v)), title: AppbarTitle(text: "lbl_atr_s".tr, margin: EdgeInsets.only(left: 8.h))); } 
/// Section Widget
Widget _buildCheckBox(BuildContext context) { return BlocSelector<DatosDelUsuarioOneBloc, DatosDelUsuarioOneState, bool?>(selector: (state) => state.checkBox, builder: (context, checkBox) {return CustomCheckboxButton(text: "msg_confiar_en_este".tr, value: checkBox, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {context.read<DatosDelUsuarioOneBloc>().add(ChangeCheckBoxEvent(value: value));});}); } 
/// Section Widget
Widget _buildEnterUserFrame(BuildContext context) { return SizedBox(height: 66.v, width: 358.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 14.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_siguiente".tr, style: TextStyle(color: appTheme.pink300, fontSize: 25.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w700)), CustomImageView(imagePath: ImageConstant.imgArrowright10x17, height: 10.v, width: 17.h, margin: EdgeInsets.only(left: 11.h, top: 8.v, bottom: 12.v))]))), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapView(context);}, child: OutlineGradientButton(padding: EdgeInsets.only(left: 4.h, top: 4.v, right: 4.h, bottom: 4.v), strokeWidth: 4.h, gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.pink300, appTheme.blue900.withOpacity(0.89), theme.colorScheme.primary]), corners: Corners(topLeft: Radius.circular(15), topRight: Radius.circular(15), bottomLeft: Radius.circular(15), bottomRight: Radius.circular(15)), child: Container(height: 66.v, width: 358.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(15.h))))))])); } 
/// Navigates to the pantallaDeBienvenidaScreen when the action is triggered.
onTapView(BuildContext context) { NavigatorService.pushNamed(AppRoutes.pantallaDeBienvenidaScreen, ); } 
 }
