import '../pedidos_cliente_registrados_page/widgets/orderdetailssection_item_widget.dart';import 'bloc/pedidos_cliente_registrados_bloc.dart';import 'models/orderdetailssection_item_model.dart';import 'models/pedidos_cliente_registrados_model.dart';import 'package:flutter/material.dart';import 'package:pedidos/core/app_export.dart';class PedidosClienteRegistradosPage extends StatefulWidget {const PedidosClienteRegistradosPage({Key? key}) : super(key: key);

@override PedidosClienteRegistradosPageState createState() =>  PedidosClienteRegistradosPageState();

static Widget builder(BuildContext context) { return BlocProvider<PedidosClienteRegistradosBloc>(create: (context) => PedidosClienteRegistradosBloc(PedidosClienteRegistradosState(pedidosClienteRegistradosModelObj: PedidosClienteRegistradosModel()))..add(PedidosClienteRegistradosInitialEvent()), child: PedidosClienteRegistradosPage()); } 
 }
class PedidosClienteRegistradosPageState extends State<PedidosClienteRegistradosPage> with  AutomaticKeepAliveClientMixin<PedidosClienteRegistradosPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 24.v), Padding(padding: EdgeInsets.symmetric(horizontal: 9.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_hoy".tr, style: TextStyle(color: theme.colorScheme.onPrimaryContainer, fontSize: 14.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w500)))), SizedBox(height: 2.v), _buildOrderDetailsSection(context), SizedBox(height: 343.v), _buildClienteMassSACSection(context)]))])))); } 
/// Section Widget
Widget _buildOrderDetailsSection(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 17.h, right: 7.h), child: BlocSelector<PedidosClienteRegistradosBloc, PedidosClienteRegistradosState, PedidosClienteRegistradosModel?>(selector: (state) => state.pedidosClienteRegistradosModelObj, builder: (context, pedidosClienteRegistradosModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 7.0.v), child: SizedBox(width: 386.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray30002)));}, itemCount: pedidosClienteRegistradosModelObj?.orderdetailssectionItemList.length ?? 0, itemBuilder: (context, index) {OrderdetailssectionItemModel model = pedidosClienteRegistradosModelObj?.orderdetailssectionItemList[index] ?? OrderdetailssectionItemModel(); return OrderdetailssectionItemWidget(model, onTapOrderDetails: () {onTapOrderDetails(context);});});})); } 
/// Section Widget
Widget _buildClienteMassSACSection(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 2.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_cliente_mass_s_a_c2".tr, style: TextStyle(color: theme.colorScheme.primary, fontSize: 16.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w900)), Text("msg_encargado_cesar".tr, style: TextStyle(color: appTheme.pink300, fontSize: 16.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w900)), Text("msg_jir_n_tomasal_145".tr, style: TextStyle(color: appTheme.pink300, fontSize: 14.fSize, fontFamily: 'Raleway', fontWeight: FontWeight.w600))])), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 12.v, width: 26.h, margin: EdgeInsets.only(top: 22.v, right: 5.h, bottom: 23.v))])); } 
/// Navigates to the pedidoFacturadoScreen when the action is triggered.
onTapOrderDetails(BuildContext context) { NavigatorService.pushNamed(AppRoutes.pedidoFacturadoScreen, ); } 
 }
